import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import MobileNavbar from "@/components/navbar/MobileNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden lg:block"><Navbar/> </div>
        <div className="block lg:hidden"><MobileNavbar/></div>
        {children}
      </body>
    </html>
  );
}
